### ISSUE TITLE
在页面销毁的时候调用EasyLoading.dismiss()无效啊

### ISSUE THREAD

**Issue by LNyears** [huangjianke/flutter_easyloading#11]
我如何在返回上一个一面的时候关闭loading啊?

**Comment by huangjianke** [comment]
@LNyears 有报错提示吗

**Comment by LNyears** [comment]
没有看到有呢，我是在进入页面init时发请求的时候拉起loading，然后在返回需要把loading关闭那我就在页面销毁的时候去掉
disniss然而不起作用


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jianke Huang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 下午2:03
收件人:&nbsp;"huangjianke/flutter_easyloading"<flutter_easyloading@noreply.github.com&gt;;
抄送:&nbsp;"N year"<1353382535@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [huangjianke/flutter_easyloading] 在页面销毁的时候调用EasyLoading.dismiss()无效啊 (#11)





 
@LNyears 有报错提示吗

**Comment by leo-shi9527** [comment]
userInteractions 这个属性好像是不work 啊

**Comment by huangjianke** [comment]
@leo-shi9527 看看代码？

**Comment by huangjianke** [comment]
@LNyears 新版已修复
