### ISSUE TITLE
EasyLoadingStyle.custom时backgroundColor设置透明无效

### ISSUE THREAD

**Issue by Pluto1219** [huangjianke/flutter_easyloading#127]
![image](https://user-images.githubusercontent.com/15402976/131603974-52cfa641-12ce-4100-8773-2b52f3402ba0.png)

![image](https://user-images.githubusercontent.com/15402976/131603980-d2b1a47f-45e2-46fe-98e1-253ad1f49522.png)
麻烦 大佬给诊断诊断

**Comment by guesspalm** [comment]
Try this.
```
..boxShadow = <BoxShadow>[]
```

**Comment by Pluto1219** [comment]
> Try this.
> 
> ```
> ..boxShadow = <BoxShadow>[]
> ```

Thank you very much.
