### ISSUE TITLE
希望可以增加自定义toast位置的api

### ISSUE THREAD

**Issue by git-maven** [huangjianke/flutter_easyloading#13]
**Describe the Feature request**
Please tell us the problem you are running into that led to you wanting
     a new feature.

这个插件都挺好用的
可惜就是缺少了oktost那种可以自定义toast位置的api
希望作者可以加入谢谢！

**Comment by huangjianke** [comment]
@git-maven 收到，后面会考虑加入

**Comment by huangjianke** [comment]
please update version 2.0.0
