### ISSUE TITLE
Scrollable Toast?

### ISSUE THREAD

**Issue by Mohammad-Adam** [huangjianke/flutter_easyloading#137]
Hi, Thanks for the hard work;

Is it possible to add an option to make the toast scrollable?

I'm trying to show a long text in a toast but I get the error: `A RenderFlex overflowed by 820 pixels on the bottom.`;

**Comment by Mohammad-Adam** [comment]
@nslog11 any suggestions here?

**Comment by jayeshinfiraise** [comment]
Can anyone help me ?  
how to show long text, at least 3 line Text ?

EasyLoading.showToast(LongTextMessage);


![Screenshot_1667294438](https://user-images.githubusercontent.com/99716331/199201939-c4ae65df-ac06-45e7-8aab-c4c22aa96e80.png)
