### ISSUE TITLE
flutter_easyLoading 导致页面卡死，无法操作，或者Toast无法展示

### ISSUE THREAD

**Issue by AnadaYuKi** [huangjianke/flutter_easyloading#142]
说一下复现步骤：Native打开Flutter页面，然后Flutter打开Native页面，此操作可以多嵌套几层，然后回到返回到之前的某一个Flutter页面，就会有大概率出现页面卡死。
注：此操作Toast不展示必现。

**Comment by nslogx** [comment]
该方案仅支持纯Flutter项目
