### ISSUE TITLE
开启loading之后,怎样避免点击穿透问题?期望页面显示loading按钮不可点击

### ISSUE THREAD

**Issue by fight1991** [huangjianke/flutter_easyloading#143]
**Describe the bug**

**Flutter/Dart info**
please run `flutter doctor` then put it here.

**Screenshots**

**Comment by DipsySu** [comment]
用maskType

**Comment by 385841539** [comment]
> 

无用

**Comment by zjkyz8** [comment]
为啥关闭了，遇到相同问题了，是有啥解法了吗？
