### ISSUE TITLE
你好，大佬，请问咱们的库，能增加gif图进行展示吗？

### ISSUE THREAD

**Issue by WangYiOS** [huangjianke/flutter_easyloading#157]
如题所示，
咱们的库能把hub更改为gif进行展示吗？
如果可以的话，具体步骤，请告知我。

祝大佬身体健康，远离疫情。

**Comment by WangYiOS** [comment]
问题已解决，代码如下
`EasyLoading.instance.loadingStyle = EasyLoadingStyle.custom;
      EasyLoading.instance.userInteractions = false;
      EasyLoading.instance.backgroundColor = Colors.transparent;
      EasyLoading.instance.indicatorColor = Colors.transparent;
      EasyLoading.instance.textColor = Colors.transparent;
      EasyLoading.instance.boxShadow = <BoxShadow>[];
      EasyLoading.instance.indicatorWidget = const Image(
        image: AssetImage("images/logo_loadding.gif"),
        width: 80,
        height: 80,
      );
      EasyLoading.show();`

大佬已经给了设置自定义控件的方法，下面这句代码至关重要，否则背景无法成为透明色
`
EasyLoading.instance.boxShadow = <BoxShadow>[];
`

**Comment by macy11** [comment]
good
