### ISSUE TITLE
测滑页面后，无法关闭loading。

### ISSUE THREAD

**Issue by wfxiaolong** [huangjianke/flutter_easyloading#16]
我尝试在deactive里边加入，dismiss，但是无法生效。（调用顺序）
手势侧滑后，无法自动关闭loading...弹窗（widget的顺序问题）
想了好久，好想目前手势返回，也没有合理的事件通知，应该就是这个解决方案的硬伤？
emememem...没有办法了...

**Comment by huangjianke** [comment]
@wfxiaolong 我先看看哈

**Comment by newsyue** [comment]
> 我尝试在deactive里边加入，dismiss，但是无法生效。（调用顺序）
> 手势侧滑后，无法自动关闭loading...弹窗（widget的顺序问题）
> 想了好久，好想目前手势返回，也没有合理的事件通知，应该就是这个解决方案的硬伤？
> emememem...没有办法了...

我也发生了和你一样的问题，然后看调试信息，显示侧滑返回时不能生成部件。

在deactive里
EasyLoading.dismiss(animation: false); animation设置为false后，问题解决。

**Comment by huangjianke** [comment]
@wfxiaolong @newsyue 新版已修复该问题，请更新至 v1.3.0
