### ISSUE TITLE
自定义的时候  背景色设置透明无效   必须要再设置 boxShadow  

### ISSUE THREAD

**Issue by desire0420** [huangjianke/flutter_easyloading#167]
EasyLoading.instance
    ..displayDuration = const Duration(milliseconds: 2000)
    ..indicatorType = EasyLoadingIndicatorType.circle
    ..loadingStyle = EasyLoadingStyle.custom
    ..maskType = EasyLoadingMaskType.black
    ..indicatorSize = 45.0
    ..radius = 10.0
    ..progressColor = Color(0xFF6CBCFC)
    ..backgroundColor = Colors.transparent
    ..boxShadow = [
      BoxShadow(color: Colors.transparent),
    ]
    ..indicatorColor = Color(0xFF6CBCFC)
    ..textColor = Color(0xFF6CBCFC)
    ..maskColor = Colors.blue.withOpacity(0.5)
    ..userInteractions = true
    ..dismissOnTap = true
    ..customAnimation = CustomAnimation();

**Comment by nslogx** [comment]
maskType = EasyLoadingMaskType.custom

**Comment by macy11** [comment]
good
