### ISSUE TITLE
Flutter 3.0 support

### ISSUE THREAD

**Issue by iamar1k92** [huangjianke/flutter_easyloading#169]
Missing support for flutter 3.0 app not building.

**Comment by longma-tech** [comment]
`/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/overlay_entry.dart:35:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
    if (SchedulerBinding.instance?.schedulerPhase ==
                         ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/overlay_entry.dart:37:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance?.addPostFrameCallback((_) {

                       ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:64:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance?.schedulerPhase ==
                       ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:101:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance?.addPostFrameCallback((_) => completer
                       ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:112:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance?.addPostFrameCallback((_) => completer
                       ^`

**Comment by longma-tech** [comment]
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/overlay_entry.dart:35:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
    if (SchedulerBinding.instance?.schedulerPhase ==
                         ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/overlay_entry.dart:37:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance?.addPostFrameCallback((_) {

                       ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:64:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance?.schedulerPhase ==
                       ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:101:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance?.addPostFrameCallback((_) => completer
                       ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:112:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance?.addPostFrameCallback((_) => completer
                       ^

**Comment by longma-tech** [comment]
Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.

**Comment by satoru260** [comment]
Just for visibility. This issue seems to be addressed in this PR https://github.com/0xPool/flutter_easyloading/pull/168. Just need to wait for that to be merged

**Comment by hkloudou** [comment]
> Just for visibility. This issue seems to be addressed in this PR #168. Just need to wait for that to be merged

i use the better way to supported flutter 3.0,PR #171,waiting the merged...

**Comment by nslogx** [comment]
done

**Comment by longma-tech** [comment]
THANKS

**Comment by iamar1k92** [comment]
obrigado
