### ISSUE TITLE
输入框长按的时候报错了，有谁解决了的啊 

### ISSUE THREAD

**Issue by 123LI** [huangjianke/flutter_easyloading#17]
如果有谁解决了，请教下怎么解决的

**Comment by jcleng** [comment]
https://github.com/huangjianke/flutter_easyloading/issues/1#issuecomment-600502599

**Comment by 123LI** [comment]
Exception when selecting text inside a FormField #1. 这里面的方法试了不行啊

**Comment by qiushouchen** [comment]
找到个临时解决办法，外层再包裹一个MaterialApp，暂时能用了，还没有测试会不会引发其他问题。
![image](https://user-images.githubusercontent.com/20275228/81495160-cc87c180-92e0-11ea-911d-5cf6ff1ad42d.png)

**Comment by sckoh** [comment]
```
MaterialApp(
  builder: (BuildContext context, Widget child) {
    return FlutterEasyLoading(
      child: child,
    );
  },
```

put FlutterEasyLoading under builder of MaterialApp will solve this issue

**Comment by huangjianke** [comment]
@sckoh thanks

**Comment by jb522185660** [comment]
这个解决方案引起另外一个导航的问题

#2      Navigator.pushNamed 
package:flutter/…/widgets/navigator.dart:1529
#3      Application.navigateTo 
package:commission/routers/application.dart:13
#4      Application.navigateToGoodsDetail 
package:commission/routers/application.dart:26
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#2b8e2
    debugOwner: GestureDetector
    state: ready
    won arena
    finalPosition: Offset(92.0, 263.3)
    finalLocalPosition: Offset(82.0, 97.3)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

**Comment by jb522185660** [comment]
The following assertion was thrown while handling a gesture:
Navigator operation requested with a context that does not include a Navigator.

The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
When the exception was thrown, this was the stack
#0      Navigator.of.<anonymous closure> 
package:flutter/…/widgets/navigator.dart:2118
#1      Navigator.of 
package:flutter/…/widgets/navigator.dart:2125
#2      Navigator.pushNamed 
package:flutter/…/widgets/navigator.dart:1529
#3      Application.navigateTo 
package:commission/routers/application.dart:13
#4      Application.navigateToGoodsDetail

**Comment by jb522185660** [comment]
> ```
> MaterialApp(
>   builder: (BuildContext context, Widget child) {
>     return FlutterEasyLoading(
>       child: child,
>     );
>   },
> ```
> 
> 
> put FlutterEasyLoading under builder of MaterialApp will solve this issue
> 
> 
> https://api.flutter.dev/flutter/material/MaterialApp/builder.html



> ```
> MaterialApp(
>   builder: (BuildContext context, Widget child) {
>     return FlutterEasyLoading(
>       child: child,
>     );
>   },
> ```
> 
> 
> put FlutterEasyLoading under builder of MaterialApp will solve this issue
> 
> 
> https://api.flutter.dev/flutter/material/MaterialApp/builder.html

How do you setup router by this solution，
I do this but course a problem,when I push or pop
"Navigator operation requested with a context that does not include a Navigator"

**Comment by farmercz** [comment]
这样修改后 路由跳转报错
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Navigator operation requested with a context that does not include a Navigator.
E/flutter ( 7698): The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.

**Comment by iBcker** [comment]
修改后同样报错 
Navigator operation requested with a context that does not include a Navigator.

**Comment by farmercz** [comment]
> 修改后同样报错
> Navigator operation requested with a context that does not include a Navigator.

每一个widget 根节点都添加一个EasyLoading

**Comment by atishoo** [comment]
> > ```
> > MaterialApp(
> >   builder: (BuildContext context, Widget child) {
> >     return FlutterEasyLoading(
> >       child: child,
> >     );
> >   },
> > ```
> > 
> > 
> > put FlutterEasyLoading under builder of MaterialApp will solve this issue
> > https://api.flutter.dev/flutter/material/MaterialApp/builder.html
> 
> 
> > ```
> > MaterialApp(
> >   builder: (BuildContext context, Widget child) {
> >     return FlutterEasyLoading(
> >       child: child,
> >     );
> >   },
> > ```
> > 
> > 
> > put FlutterEasyLoading under builder of MaterialApp will solve this issue
> > https://api.flutter.dev/flutter/material/MaterialApp/builder.html
> 
> 
> How do you setup router by this solution，
> 
> I do this but course a problem,when I push or pop
> 
> "Navigator operation requested with a context that does not include a Navigator"

it works!
but unfortunately，it appears double yellow underlines.

**Comment by atishoo** [comment]
this is the correct solution:
```
builder: (BuildContext context, Widget child) {
    return Material(
        child: FlutterEasyLoading(
            child: child,
        ),
    );
}
```
add above code to your MaterialApp😜😜😜

**Comment by CoderJasons** [comment]
> this is the correct solution:
> 
> ```
> builder: (BuildContext context, Widget child) {
>     return Material(
>         child: FlutterEasyLoading(
>             child: child,
>         ),
>     );
> }
> ```
> 
> add above code to your MaterialApp😜😜😜
放在MaterialApp的child，showtoast的时候文案下方会有一个黄色的警告线的问题有遇到过吗

**Comment by fangshengfy** [comment]
> > this is the correct solution:
> > ```
> > builder: (BuildContext context, Widget child) {
> >     return Material(
> >         child: FlutterEasyLoading(
> >             child: child,
> >         ),
> >     );
> > }
> > ```
> > 
> > 
> > add above code to your MaterialApp😜😜😜
> > 放在MaterialApp的child，showtoast的时候文案下方会有一个黄色的警告线的问题有遇到过吗

我也遇到了，请问怎么解决

**Comment by atishoo** [comment]
不是放在child，是放在builder

**Comment by jasonW9527** [comment]
> 
> 
> this is the correct solution:
> 
> ```
> builder: (BuildContext context, Widget child) {
>     return Material(
>         child: FlutterEasyLoading(
>             child: child,
>         ),
>     );
> }
> ```
> 
> add above code to your MaterialApp😜😜😜
 good，it works!

**Comment by silentchild** [comment]
> > > this is the correct solution:
> > > ```
> > > builder: (BuildContext context, Widget child) {
> > >     return Material(
> > >         child: FlutterEasyLoading(
> > >             child: child,
> > >         ),
> > >     );
> > > }
> > > ```
> > > 
> > > 
> > > add above code to your MaterialApp😜😜😜
> > > 放在MaterialApp的child，showtoast的时候文案下方会有一个黄色的警告线的问题有遇到过吗
> 
> 我也遇到了，请问怎么解决

一样，谁解决了？

**Comment by yakubpashask** [comment]
> > ```
> > MaterialApp(
> >   builder: (BuildContext context, Widget child) {
> >     return FlutterEasyLoading(
> >       child: child,
> >     );
> >   },
> > ```
> > 
> > 
> > put FlutterEasyLoading under builder of MaterialApp will solve this issue
> > https://api.flutter.dev/flutter/material/MaterialApp/builder.html
> 
> 
> > ```
> > MaterialApp(
> >   builder: (BuildContext context, Widget child) {
> >     return FlutterEasyLoading(
> >       child: child,
> >     );
> >   },
> > ```
> > 
> > 
> > put FlutterEasyLoading under builder of MaterialApp will solve this issue
> > https://api.flutter.dev/flutter/material/MaterialApp/builder.html
> 
> 
> How do you setup router by this solution，
> 
> I do this but course a problem,when I push or pop
> 
> "Navigator operation requested with a context that does not include a Navigator"

Did you get any resolution for the navigator?

**Comment by CNAD666** [comment]
这问题确实坑，综合上面几位歪果仁提出，和自己尝试，用下面的代码可以解决长按报错，Navigator报错问题，页面必须要向上遍历得到Context，Page要写在Home里面，EasyLoading写在builder里面就行了，把child带下去
`class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(
          child: child,
        );
      },
    );
  }
}`

**Comment by erayhamurlu** [comment]
Just add to bottom  GlobalCupertinoLocalizations.delegate where is  GlobalMaterialLocalizations.delegate
