### ISSUE TITLE
大佬好，希望增加loading期间无法点击背景的功能

### ISSUE THREAD

**Issue by chenparty** [huangjianke/flutter_easyloading#18]
loading期间，整个界面的所有按钮都是可点击的，希望有类似barrierDismiss的功能。

**Comment by huangjianke** [comment]
@chenparty 

设置这个

```dart
/// should allow user interactions while loading is displayed.
bool userInteractions;
```

**Comment by chenparty** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jianke Huang"<notifications@github.com&gt;; 
发送时间: 2020年5月12日(星期二) 晚上8:48
收件人: "huangjianke/flutter_easyloading"<flutter_easyloading@noreply.github.com&gt;; 
抄送: "Chenparty"<870300816@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [huangjianke/flutter_easyloading] 大佬好，希望增加loading期间无法点击背景的功能 (#18)





 
@chenparty
 
设置这个
 /// should allow user interactions while loading is displayed. bool userInteractions;
