### ISSUE TITLE
【紧急】操作TextField导致页面崩溃

### ISSUE THREAD

**Issue by qcdys** [huangjianke/flutter_easyloading#19]
https://github.com/OpenFlutter/flutter_oktoast/issues/46
错误与链接中一致

Channel stable, v1.17.0

希望大佬可以修复一下 多谢

**Comment by jackTang11** [comment]
同样的问题，求解决

**Comment by jackTang11** [comment]
> [OpenFlutter/flutter_oktoast#46](https://github.com/OpenFlutter/flutter_oktoast/issues/46)
> 错误与链接中一致
> 
> Channel stable, v1.17.0
> 
> 希望大佬可以修复一下 多谢


> [OpenFlutter/flutter_oktoast#46](https://github.com/OpenFlutter/flutter_oktoast/issues/46)
> 错误与链接中一致
> 
> Channel stable, v1.17.0
> 
> 希望大佬可以修复一下 多谢

https://github.com/huangjianke/flutter_easyloading/issues/17#issuecomment-626452507

**Comment by jackTang11** [comment]
> [OpenFlutter/flutter_oktoast#46](https://github.com/OpenFlutter/flutter_oktoast/issues/46)
> 错误与链接中一致
> 
> Channel stable, v1.17.0
> 
> 希望大佬可以修复一下 多谢

https://github.com/huangjianke/flutter_easyloading/issues/17#issuecomment-626452507

**Comment by huangjianke** [comment]
#17
