### ISSUE TITLE
Loader not being shown on top

### ISSUE THREAD

**Issue by Ioana-Sofia-Lazar** [huangjianke/flutter_easyloading#201]
**Describe the bug**
I've been using this library for a while, but recently I've discovered that the loader is not shown on the top-most screen. Not sure if I'd done anything to break it, but I don't think I've changed the config since the beginning.

**Flutter/Dart info**
[√] Flutter (Channel master, 3.5.0-8.0.pre.7, on Microsoft Windows [Version 10.0.22000.1455], locale en-US)
    • Flutter version 3.5.0-8.0.pre.7 on channel master at C:\src\flutter_windows_3.3.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a707d05e9d (4 months ago), 2022-10-14 19:48:26 -0400
    • Engine revision 59dea4cddd
    • Dart version 2.19.0 (build 2.19.0-312.0.dev)
    • DevTools version 2.18.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:/Users/Ioana/AppData/Local/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:/Users/Ioana/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\Ioana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM S908B (mobile) • 192.168.1.33:37111 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.22000.1455]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Screenshots**
The top-most screen has a transparent background (with a filter applied). Through it you can see the loader being shown behind it. 

https://user-images.githubusercontent.com/23142106/218322980-4760b676-2b0c-4d3d-854c-b873dcd397f1.mp4

Thank you,
Ioana

**Comment by mikhael28** [comment]
+1 on my end here. Considering migrating to a different library, this is a pretty big issue.

**Comment by Ioana-Sofia-Lazar** [comment]
@mikhael28 in case you still have the issue, I fixed it by following the latest instructions:
- added `EasyLoading.init()` in the MaterialApp builder
- removed the use of `FlutterEasyLoading`
These have probably changed with a previous release.

**Comment by mikhael28** [comment]
@Ioana-Sofia-Lazar I'm not sure this is a fix that works for me. For one, I always had EasyLoading.init() in the MaterialBuilder, and second - I've never used the FlutterEasyLoading class, I've always used the EasyLoading class. Is that what you meant by 1`removed the user of FlutterEasyLoading` ?
