### ISSUE TITLE
Prevent touch when clicking on the background of the loading widget

### ISSUE THREAD

**Issue by bahman2000** [huangjianke/flutter_easyloading#204]
What it should normally be, background widgets should not be clickable when the loading widget is open. So what I want is to block the click of a TextField, Button, etc on the background of the loading widget.

**Comment by berkanaslan** [comment]
This is already developed feature, not an issue.

```
  void configLoadingIndicator() {
    EasyLoading.instance
      ..userInteractions = false
  }
```

then call `configLoadingIndicator()` in main.dart.

**Comment by bahman2000** [comment]
@berkanaslan Yes you are right! Thank you for your help.
