### ISSUE TITLE
怎么把文字的黄色双下划线去掉

### ISSUE THREAD

**Issue by Android-wangmeng** [huangjianke/flutter_easyloading#23]
如题，谢谢！

**Comment by 190709670** [comment]
如果在materialApp上层是没有黄色下划线的,如果在materialApp下层的话,出现黄色双下划线,同求解决

**Comment by 190709670** [comment]
Text不在materialApp里面时,会自带双下划线,在text里面加入装饰器 decoration: TextDecoration.none 就好了.希望博主尽快更新修复次问题...

**Comment by HLQ-Struggle** [comment]
我现在是直接 show 了，😂，不添加提示语了。

```
EasyLoading.show();
```

补充下效果截图，而且发现这个字貌似也被加粗了。

![image](https://user-images.githubusercontent.com/19400093/82730814-1cc93f80-9d35-11ea-92ef-2be52e4e8e64.png)


当前使用版本：

```
flutter_easyloading: ^1.1.4
```

附上实际使用代码：

```
class LoginPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    mContext = context;
    return new FlutterEasyLoading(
        child: MaterialApp(
      home: _LoginPage(),
    ));
  }
}
```

**Comment by Linzdigr** [comment]
https://stackoverflow.com/questions/47114639/yellow-lines-under-text-widgets-in-flutter

Same here, but with `FlutterEasyLoading` in a `MaterialApp` builder:

```dart
// [...]

class CherryApp extends StatelessWidget {
  // Root App
// [...]
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: Constants.appName,
      initialRoute: Routes.login,
      builder: (BuildContext context, Widget child) {
        return FlutterEasyLoading(
            child: ChangeNotifierProvider<AppState>(
              create: (_) => AppState(),
              child: child
            )
        );
      }
// [...]
    );
  }
}
```

**Comment by yezibao1991** [comment]
> https://stackoverflow.com/questions/47114639/yellow-lines-under-text-widgets-in-flutter
> 
> Same here, but with `FlutterEasyLoading` in a `MaterialApp` builder:
> 
> ```dart
> // [...]
> 
> class CherryApp extends StatelessWidget {
>   // Root App
> // [...]
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: Constants.appName,
>       initialRoute: Routes.login,
>       builder: (BuildContext context, Widget child) {
>         return FlutterEasyLoading(
>             child: ChangeNotifierProvider<AppState>(
>               create: (_) => AppState(),
>               child: child
>             )
>         );
>       }
> // [...]
>     );
>   }
> }
> ```

builder: (BuildContext context, Widget child) {
          OrientationPlugin.setPreferredOrientations([DeviceOrientation.portraitUp]);
          return Material(
            type: MaterialType.transparency,
            child: FlutterEasyLoading(
              child: child,
            ),
          );
        }

**Comment by huangjianke** [comment]
@190709670 @Android-wangmeng 新版已经修复了
