### ISSUE TITLE
存在并发问题

### ISSUE THREAD

**Issue by long51xy** [huangjianke/flutter_easyloading#24]
当一个EasyLoading.showSuccess('11111');连续除非二次就报错，比如
` onTap: () {
  print('Get OTP Code');
  EasyLoading.showSuccess('11111');
}`
按钮联系点击二次出现异常
No MediaQuery widget found.
The relevant error-causing widget was
    FlutterEasyLoading

**Comment by long51xy** [comment]
感觉你写的插件不错，不用自己写了，如果这个并非问题我解决我们还得封装一层队列排队去控制显示，这样就麻烦了

**Comment by navyzhou926** [comment]
在一个页面中快速点击不能的输入框TextField，则会报错

**Comment by navyzhou926** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#8b39f](dirty, state: _OverlayEntryWidgetState#4272c):
No MediaQuery widget found.

_OverlayEntryWidget widgets require a MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was: _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#8b39f]
  dirty
  state: _OverlayEntryWidgetState#4272c
The ownership chain for the affected widget is: "_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#8b39f] ← _Theatre ← Overlay ← Directionality ← FlutterEasyLoading ← MyApp ← [root]"

Typically, the MediaQuery widget is introduced by the MaterialApp or WidgetsApp widget at the top of your application widget tree.

The relevant error-causing widget was: 
  FlutterEasyLoading file:///Users/apple/git/flutter_app/lib/main.dart:117:16
When the exception was thrown, this was the stack: 
#0      debugCheckHasMediaQuery.<anonymous closure> (package:flutter/src/widgets/debug.dart:215:7)
#1      debugCheckHasMediaQuery (package:flutter/src/widgets/debug.dart:227:4)
#2      _MaterialTextSelectionControls.buildToolbar (package:flutter/src/material/text_selection.dart:645:12)
#3      TextSelectionOverlay._buildToolbar (package:flutter/src/widgets/text_selection.dart:556:34)
#4      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:177:34)
