### ISSUE TITLE
fluro跳转后 show出现在上一页

### ISSUE THREAD

**Issue by zhujiahong** [huangjianke/flutter_easyloading#30]
大佬这是报错的内容，push以后show要么没反应，要么出现在上一页，好像是丢失context造成的，不知道有什么办法可以解决
════════ Exception caught by gesture ═══════════════════════════════════════════

The following assertion was thrown while handling a gesture:

Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack

#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> 
package:flutter/…/widgets/framework.dart:3508

#1      Element._debugCheckStateIsActiveForAncestorLookup 
package:flutter/…/widgets/framework.dart:3522

#2      Element.findAncestorStateOfType 
package:flutter/…/widgets/framework.dart:3641

#3      Overlay.of 
package:flutter/…/widgets/overlay.dart:237

#4      EasyLoading._show 
package:flutter_easyloading/src/easy_loading.dart:338

...

Handler: "onTap"

Recognizer: TapGestureRecognizer#ece18

    debugOwner: GestureDetector

    state: ready

    won arena

    finalPosition: Offset(256.3, 404.3)

    finalLocalPosition: Offset(256.3, 54.3)

    button: 1

    sent tap down

**Comment by shandengx** [comment]
检查一下，有没有写以下这段代码：
`builder: (context, child) {
        return Material(
          type: MaterialType.transparency,
          child: FlutterEasyLoading(
            child: child,
          ),
        );
      }`
刚开始我也碰到跟你一样的问题，后来发现是这段代码没有写。
