### ISSUE TITLE
异步调用出问题

### ISSUE THREAD

**Issue by cctvbtv123456** [huangjianke/flutter_easyloading#31]
这里调用
FutureBuilder<Map>(
        future: Api.post_preview_study_home(params),

这是网络请求(代码执行到这EasyLoading.show(status: '加载中') 就不往下走了，什么原因  )
static Future<Map> post_preview_study_home(Map params) async {
    print('params = $params');
    EasyLoading.show(status: '加载中');
    print(00000);
    Response response = await http.post('/preview_study/home', params);
    print(111111);
    if (response.statusCode == 200) {
      print(222222);
      EasyLoading.dismiss();
      Map dataMap = response.data;
      return dataMap['data'];
    } else {
      EasyLoading.dismiss();
      return null;
    }
  }

**Comment by RuErJieFei** [comment]
我也遇到了相同的问题

**Comment by huangjianke** [comment]
请试试v1.3.0，如还有问题，请重新开个issue
