### ISSUE TITLE
放在MaterialApp外层长按输入框报错，放到里面文字下方有下划线，求修复

### ISSUE THREAD

**Issue by silentchild** [huangjianke/flutter_easyloading#32]
MaterialApp(
          builder: (context, child) {
            //FlutterEasyLoading放在这里解决放到外层输入框长按报错
            return FlutterEasyLoading(child: child);
          },

这样写会有下划线，不这样写长按输入框报错，求解决啊！！！

**Comment by mdddj** [comment]
解决方案
```
 builder: (BuildContext context, Widget child) {
        return Material(
          type: MaterialType.transparency,
          child: FlutterEasyLoading(
            child: child,
          ),
        );
      },
```

**Comment by silentchild** [comment]
> type: MaterialType.transparency,

好的，谢谢，不过我发现不加type: MaterialType.transparency,也可以，不知道加这个的作用是？

**Comment by huangjianke** [comment]
@silentchild 新版已经修复了，原因是：Text 属于Material 风格下的组件，如果根节点不是Material相关组件，则会使用默认带黄色下划线的格式
