### ISSUE TITLE
显示加载中的时候 

### ISSUE THREAD

**Issue by liyunfu** [huangjianke/flutter_easyloading#35]
显示加载中的时候  能不能按返回键就关闭

**Comment by huangjianke** [comment]
> 显示加载中的时候 能不能按返回键就关闭

这个应该是属于业务逻辑，可以监听返回键事件执行 `dismss` 方法

**Comment by OCer** [comment]
实际上 不管是什么情况 当页面跳转的时候  肯定是要把当前的HUD关闭掉的啊  不然我每个页面都去监听 代码冗余就太多了  一个项目 最后发现 每个路由都写满了监听 - - @kokohuang
