### ISSUE TITLE
Can I disable user interaction when loading?

### ISSUE THREAD

**Issue by Hassanmsaid** [huangjianke/flutter_easyloading#37]
I want to prevent the user from touching or interacting with any part of the screen while loading is shown(like progress dialog in Android). Is there any way I can do that?

**Comment by Hassanmsaid** [comment]
**Solved.** I found the property userInteractions.

**Comment by bhargavsejpalindianic** [comment]
can we disable the back button while loading?

**Comment by ddxl123** [comment]
> 

help
