### ISSUE TITLE
Touch to dismiss

### ISSUE THREAD

**Issue by meeftah** [huangjianke/flutter_easyloading#39]
Can I get a feature to dismiss with a touch inside or outside the loading dialog

**Comment by huangjianke** [comment]
@meeftah you can set `userInteractions` option `true`

**Comment by meeftah** [comment]
when I set userInteractions to true, it still there, even I move to another page....I mean when I touch the dialog, it should be dismissed

**Comment by huangjianke** [comment]
sorry...
when  set `userInteractions`  to true, will allow user interactions while loading is displayed, but not dismiss
