### ISSUE TITLE
需要一个简单的toast方法 

### ISSUE THREAD

**Issue by qcdys** [huangjianke/flutter_easyloading#4]

**Comment by huangjianke** [comment]
@qcdys 不需要图标的那种？还是？

**Comment by qcdys** [comment]
@huangjianke 是的 不需要图标的那种 
10000个人在等你

**Comment by huangjianke** [comment]
@qcdys 考虑下个版本加入

**Comment by qcdys** [comment]
> @qcdys考虑下个版本加入

谢谢大佬

**Comment by huangjianke** [comment]
> > @qcdys考虑下个版本加入
> 
> 谢谢大佬

最新版已经加好了

`EasyLoading.showToast('Toast');`
