### ISSUE TITLE
FlutterEasyLoading覆盖app组件是每个页面都需要吗？

### ISSUE THREAD

**Issue by shelby-yao** [huangjianke/flutter_easyloading#40]
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (BuildContext context, Widget child) {
        /// 确保 loading 组件能覆盖在其他组件之上.
        return FlutterEasyLoading(
          child: MyHomePage(title: 'Flutter EasyLoading'),
        );
      },
    );
  }
}

**Comment by shandengx** [comment]
不需要，入口builder里已经写了相应代码了。
