### ISSUE TITLE
flutter: Another exception was thrown: setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by judastatus** [huangjianke/flutter_easyloading#41]
你好，我在发起网络请求的时候，使用 EasyLoading.show(status: "Loading...");然后报如下错误。请问，我的问题出在哪里？

**Describe the bug**
flutter: Another exception was thrown: setState() or markNeedsBuild() called during build.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-08 at 08 13 06](https://user-images.githubusercontent.com/15098424/92421501-5f5f3c80-f1ab-11ea-9296-c1d26807a2d6.png)

**Comment by czero1995** [comment]
我也是遇到这个问题

**Comment by judastatus** [comment]
@override
  void initState() {
    // TODO: implement initState
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      EasyLoading.show(status: "Loading...");
    });
    super.initState();
  }
