### ISSUE TITLE
Unhandled Exception: setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by czero1995** [huangjianke/flutter_easyloading#43]
i use package,and run  EasyLoading.show(status: 'loading...')，get this error, how fixed it？
![image](https://user-images.githubusercontent.com/11902423/92544767-4032de80-f281-11ea-892a-64d20b36d92d.png)

![image](https://user-images.githubusercontent.com/11902423/92544736-2ee9d200-f281-11ea-8fe9-8ec056df4506.png)

**Comment by judastatus** [comment]
@override
  void initState() {
    // TODO: implement initState
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      EasyLoading.show(status: "Loading...");
    });
    _tabController = TabController(length: 3, vsync: this);
    super.initState();
  }

你把showLoading的方法写在 initState() 里试下
