### ISSUE TITLE
从页面到另一个页面，页面无法显示easyloading

### ISSUE THREAD

**Issue by Tangshenghao1** [huangjianke/flutter_easyloading#44]
page1 被FlutterEasyLoading包裹 跳到 同样被FlutterEasyLoading包裹的page2 ， page1可以显示easyloading，page2无法显示.
`import 'package:flutter/material.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(),
      home: PageOne(),
    );
  }
}

class PageOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FlutterEasyLoading(
      child: Scaffold(
        appBar: AppBar(),
        body: Container(
          child: Column(
            children: <Widget>[
              FlatButton(
                child: Text('show loading'),
                onPressed: (){
                  EasyLoading.show();
                  Future.delayed(Duration(seconds: 2), (){
                    EasyLoading.dismiss();
                  });
                },
              ),
              FlatButton(
                child: Text('page2'),
                onPressed: (){
                  Navigator.push( context,
                      MaterialPageRoute(builder: (context) {
                        return PageTwo();
                      }));
                  },
              )
            ],
          ),
        ),
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: Container(
          child: FlatButton(
            child: Text('show loading'),
            onPressed: (){
              EasyLoading.show();
              Future.delayed(Duration(seconds: 2), (){
                EasyLoading.dismiss();
              });
            },
          ),
        )
    );
  }
}
`

**Comment by huangjianke** [comment]
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(
          child: MyHomePage(title: 'Flutter EasyLoading'),
        );
      },
    );
  }
}
```

请使用这种方式来初始化
