### ISSUE TITLE
为什么我用这种方式初始化会报错

### ISSUE THREAD

**Issue by WilliamsLee** [huangjianke/flutter_easyloading#46]
![1600828630(1)](https://user-images.githubusercontent.com/22174430/93958438-143b5100-fd89-11ea-97ce-e9a6d4a06a19.png)
![1600828722(1)](https://user-images.githubusercontent.com/22174430/93958442-17364180-fd89-11ea-94dc-e2a39ab9eda0.jpg)

**Comment by huangjianke** [comment]
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(
          child: MyHomePage(title: 'Flutter EasyLoading'),
        );
      },
    );
  }
}
```

试试这样，`MaterialApp ` 作为根节点

**Comment by WilliamsLee** [comment]
> ```dart
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter EasyLoading',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       builder: (BuildContext context, Widget child) {
>         /// make sure that loading can be displayed in front of all other widgets
>         return FlutterEasyLoading(
>           child: MyHomePage(title: 'Flutter EasyLoading'),
>         );
>       },
>     );
>   }
> }
> ```
> 
> 试试这样，`MaterialApp ` 作为根节点

一样的，这个图我截错了，就是materialApp为根节点
![image](https://user-images.githubusercontent.com/22174430/93958949-3f727000-fd8a-11ea-9bbc-f304f50f1ba3.png)

**Comment by WilliamsLee** [comment]
> ```dart
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter EasyLoading',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       builder: (BuildContext context, Widget child) {
>         /// make sure that loading can be displayed in front of all other widgets
>         return FlutterEasyLoading(
>           child: MyHomePage(title: 'Flutter EasyLoading'),
>         );
>       },
>     );
>   }
> }
> ```
> 
> 试试这样，`MaterialApp ` 作为根节点

这个child不管指定哪个页面，在那个页面里面跳转新页面都会出现这个错误

**Comment by huangjianke** [comment]
@WilliamsLee 
```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(child: child);
      },
    );
  }
}
```
麻烦再试试这样初始化

**Comment by WilliamsLee** [comment]
这种方式可以，但是有另一个问题，我进入一个页面的时候需要请求接口获取数据，这时候showloading会出现这个错误信息
`[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'findAncestorStateOfType' was called on null.`

**Comment by WilliamsLee** [comment]
> @WilliamsLee
> 
> ```dart
> class MyApp extends StatelessWidget {
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter EasyLoading',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter EasyLoading'),
>       builder: (BuildContext context, Widget child) {
>         /// make sure that loading can be displayed in front of all other widgets
>         return FlutterEasyLoading(child: child);
>       },
>     );
>   }
> }
> ```
> 
> 麻烦再试试这样初始化

这种方式可以，但是我刚进入一个页面时候showloading，会出现这个错误提示，loading也不会出现，比如刚进入页面需要请求接口获取数据

通过按钮点击或者其他方式可以触发

`[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'findAncestorStateOfType' was called on null.`

**Comment by huangjianke** [comment]
@WilliamsLee 是在 `initState` 方法中调用么，如果是，请先使用：

```dart
    WidgetsBinding.instance.addPostFrameCallback((_) {
      EasyLoading.show();
    });
```

这个问题会在新版解决

**Comment by WilliamsLee** [comment]
> @WilliamsLee 是在 `initState` 方法中调用么，如果是，请先使用：
> 
> ```dart
>     WidgetsBinding.instance.addPostFrameCallback((_) {
>       EasyLoading.show();
>     });
> ```
> 
> 这个问题会在新版解决

他还是会报错，但是不会中断程序继续运行是吗？

**Comment by huangjianke** [comment]
v1.3.0 已更新，如果还有问题请重新开个issue @WilliamsLee
