### ISSUE TITLE
some error in 1.3.0

### ISSUE THREAD

**Issue by 631366957** [huangjianke/flutter_easyloading#47]
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/painting/alignment.dart': Failed assertion: line 530 pos 12: 'direction !=
flutter: null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   Overlay
flutter:   file:///Users/temp/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-1.3.0/lib/src/widgets/loading.dart:38:14
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      AlignmentDirectional.resolve (package:flutter/src/painting/alignment.dart:530:12)
flutter: #3      RenderStack._resolve (package:flutter/src/rendering/stack.dart:355:36)
flutter: #4      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:470:5)
flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
flutter: #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
flutter: #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
flutter: #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #11     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
flutter: #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
flutter: #13     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
flutter: #14     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
flutter: #15     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
flutter: #16     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
flutter: #17     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
flutter: #18     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #19     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
flutter: #20     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
flutter: #21     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
flutter: #30     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
flutter: #31     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
flutter: #32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
flutter: (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderStack#e0869 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: Stack ← _Theatre ← Overlay ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
flutter:     _InkFeatures-[GlobalKey#1dbf2 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
flutter:     PhysicalModel ← AnimatedPhysicalModel ← Material ← FlutterEasyLoading ← MyApp ← ⋯
flutter:   parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: BoxConstraints(w=375.0, h=667.0)
flutter:   size: MISSING
flutter:   alignment: AlignmentDirectional.topStart
flutter:   textDirection: null
flutter:   fit: expand
flutter:   overflow: clip
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child 1: RenderSemanticsAnnotations#c98e3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child: RenderSemanticsAnnotations#dca6e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: _RenderTheatre#d5891 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           onstage: RenderStack#fa05d NEEDS-LAYOUT NEEDS-PAINT
flutter:           no offstage children
flutter:     child 2: RenderLimitedBox#a8688 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child: RenderConstrainedBox#30926 NEEDS-LAYOUT NEEDS-PAINT
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderBox was not laid out: RenderStack#e0869 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderTheatre#daba9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#78397 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 1702 pos 12: 'hasSize': is not true.
flutter: flutter main page name is default
flutter: ---initState
flutter: ---didChangeDependencies
flutter: FlutterBoost#onShownContainerChanged old:null now:default
flutter: Another exception was thrown: MissingPluginException(No implementation found for method listen on channel samples.flutter.dev/getLoginData)
flutter: Another exception was thrown: Updated layout information required for RenderSemanticsAnnotations#c98e3 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
flutter: Another exception was thrown: RenderBox was not laid out: RenderPhysicalModel#cde1d
flutter: Another exception was thrown: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 1702 pos 12: 'hasSize': is not true.
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Cannot hit test a render box with no size.
The hitTest() method was called on this RenderBox: RenderPhysicalModel#cde1d:
  needs compositing
  creator: PhysicalModel ← AnimatedPhysicalModel ← Material ← FlutterEasyLoading ← MyApp ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=375.0, h=667.0)
  size: MISSING
  elevation: 0.0
  color: Color(0xfffafafa)
  shadowColor: Color(0xfffafafa)
  shape: BoxShape.rectangle
  borderRadius: BorderRadius.zero
Although this node is not marked as needing layout, its size is not set.
A RenderBox object must have an explicit size before it can be hit-tested. Make sure that the RenderBox in question sets its size during layout.
#0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:2118:9)
#1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2133:6)
#2      RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1722:18)
#3      Re<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Cannot hit test a render box with no size.
The hitTest() method was called on this RenderBox: RenderPhysicalModel#cde1d:
  needs compositing
  creator: PhysicalModel ← AnimatedPhysicalModel ← Material ← FlutterEasyLoading ← MyApp ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=375.0, h=667.0)
  size: MISSING
  elevation: 0.0
  color: Color(0xfffafafa)
  shadowColor: Color(0xfffafafa)
  shape: BoxShape.rectangle
  borderRadius: BorderRadius.zero
Although this node is not marked as needing layout, its size is not set.
A RenderBox object must have an explicit size before it can be hit-tested. Make sure that the RenderBox in question sets its size during layout.
#0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:2118:9)
#1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2133:6)
#2      RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1722:18)
#3      Re<…>

**Comment by huangjianke** [comment]
you should init `FlutterEasyLoading` like this:

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(child: child);
      },
    );
  }
}
```

**Comment by 631366957** [comment]
> you should init `FlutterEasyLoading` like this:
> 
> ```dart
> class MyApp extends StatelessWidget {
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter EasyLoading',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter EasyLoading'),
>       builder: (BuildContext context, Widget child) {
>         /// make sure that loading can be displayed in front of all other widgets
>         return FlutterEasyLoading(child: child);
>       },
>     );
>   }
> }
> ```

it is ok
