### ISSUE TITLE
EasyLoading.showToast 增加一个显示位置的参数

### ISSUE THREAD

**Issue by jeromekai** [huangjianke/flutter_easyloading#49]
希望扩展一个参数用于调整弹出位置

**Comment by huangjianke** [comment]
@jeromekai 下个版本就有了

**Comment by huangjianke** [comment]
@jeromekai 新版已发布

**Comment by jeromekai** [comment]
谢谢，看到代码有添加&nbsp; enum支持，toast能否有一些独特的需求，比如背景色，文字颜色，圆角。
如果全局配置,会不会影响其他效果，或者将widget抛出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huangjianke/flutter_easyloading"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月28日(星期一) 下午3:14
收件人:&nbsp;"huangjianke/flutter_easyloading"<flutter_easyloading@noreply.github.com&gt;;
抄送:&nbsp;"Jerome"<1641194779@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [huangjianke/flutter_easyloading] EasyLoading.showToast 增加一个显示位置的参数 (#49)





 
@jeromekai 新版已发布

**Comment by huangjianke** [comment]
@jeromekai 目前没有为 Toast 做单独的样式配置，都是全局统一的，后期看看大家的需求吧
