### ISSUE TITLE
EasyLoading.show 增加个超时时间

### ISSUE THREAD

**Issue by chd999** [huangjianke/flutter_easyloading#5]
希望 EasyLoading.show 增加个超时时间

**Comment by huangjianke** [comment]
@chd999 可以描述具体点需求么？

**Comment by chd999** [comment]
比如在 5秒后，自动关闭loading框，  防止某些情况下，没有代码关闭longding框，一直是longding框，比如某些捕获不到的异常。

**Comment by chd999** [comment]
@huangjianke   大概就是上面的具体描述了。

**Comment by chd999** [comment]
最好是自动关闭本次的longding框,   比如 EasyLoading.show 我设置的超时时间是30秒， 代码关闭它是在第9秒的时候， 再第21秒的时候，我又打开了一个新的EasyLoading.show， 第30秒的时候， 不希望受第一次EasyLoading.show超时时间30秒的影响，不希望因为第一个Loading框的超时时间而关闭了第二个Loading框， 这可能是要考虑到的问题。

**Comment by huangjianke** [comment]
> 比如在 5秒后，自动关闭loading框， 防止某些情况下，没有代码关闭longding框，一直是longding框，比如某些捕获不到的异常。

这个我考虑下，谢谢
