### ISSUE TITLE
Dialog中使用show不出来，没有报错

### ISSUE THREAD

**Issue by liangtian123** [huangjianke/flutter_easyloading#50]
之前在Dialog中可以正常使用，因为我是点击按钮直接弹窗，没有异步操作，但是现在我需要使用Dio框架请求数据回来后再弹窗，这时无论我怎么改，穷尽我能想象到的原因都无法解决，然后改用1.3.0版后可以show出来了，但是弹窗的遮罩层却变成不透明的了，像是给Dialog嵌了一层Material，并且之前的一些可以正常使用的非Dialog场景又出了问题，show不出来！
刚转flutter没多久，求大佬解救

**Comment by liangtian123** [comment]
![image](https://user-images.githubusercontent.com/29178702/94445022-8e306780-01d9-11eb-9135-fc1261a7f073.png)
![image](https://user-images.githubusercontent.com/29178702/94445153-b28c4400-01d9-11eb-9dec-b7620154b437.png)
同样的地方，我只要不是在异步操作中弹Dialog，就可以正常show Loading

**Comment by huangjianke** [comment]
@liangtian123 

可否提供一个小demo？

**Comment by liangtian123** [comment]
可以，我晚点给你

**Comment by liangtian123** [comment]
已经解决，我尝试把所有外层嵌套的FlutterEasyLoading去掉，只在MaterialApp的builder嵌套FlutterEasyLoading，问题解决！之前主要因为使用了IndexedStack，然后它的所有子widget里都嵌套了FlutterEasyLoading，导致非常混乱
`builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return Material(child: FlutterEasyLoading(child: child));
      },`

**Comment by huangjianke** [comment]
全局只需要初始化一次

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(child: child);
      },
    );
  }
}
```

**Comment by CNMathon** [comment]
我似乎遇到了同样的问题，无异步操作则可以正常使用，一旦放置于异步请求后便无法正常调用，且无任何内部报错被抛出。

**Comment by CNMathon** [comment]
> 全局只需要初始化一次
> 
> ```dart
> class MyApp extends StatelessWidget {
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter EasyLoading',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter EasyLoading'),
>       builder: (BuildContext context, Widget child) {
>         /// make sure that loading can be displayed in front of all other widgets
>         return FlutterEasyLoading(child: child);
>       },
>     );
>   }
> }
> ```

是的，我是这样操作的，只有一次build。

**Comment by huangjianke** [comment]
@CNMathon 可否提供一个demo？

**Comment by HeyuanXie** [comment]
@kokohuang 大佬救命，我这一样，只初始化了一次，异步中show不出来
