### ISSUE TITLE
关于遮罩的两个建议

### ISSUE THREAD

**Issue by MX8CLUB** [huangjianke/flutter_easyloading#54]
1、希望在show方法中能添加maskType的参数，不然每次都需要使用instance修改maskType，在使用结束后再次修改maskType。
2、在开启遮罩时程序还是可以响应系统页面返回操作，希望能够在遮罩开启时不能进行返回操作。

**Comment by huangjianke** [comment]
@MX8CLUB 很好的建议，谢谢，争取下个版本加上

**Comment by zyzhangjian** [comment]
有个比较低级的问题，想问一个，我现在在用flutter-boost框架，初始化是在MaterialApp的builder中，builder: FlutterBoost.init(postPush: _onRoutePushed), 然后easyloading也要在相同的地方初始化，就有冲突了，不能同时初始化boost跟easyloading，请问这个问题应该怎么解决啊，小白勿喷，谢谢！

**Comment by huangjianke** [comment]
@zyzhangjian 
```dart
        builder: FlutterBoost.init(
          postPush: _onRoutePushed,
          builder: (_, child) {
            return FlutterEasyLoading(child: child);
          },
        )
```

可以这样初始化，但目前结合`FlutterBoost` 框架使用会存在问题

**Comment by zyzhangjian** [comment]
非常感谢，能请教下会存在什么问题么？

**Comment by huangjianke** [comment]
第一点已添加，第二点后期解决，暂时没有什么好的方法
