### ISSUE TITLE
在initState使用报错

### ISSUE THREAD

**Issue by CoderTitan** [huangjianke/flutter_easyloading#55]
为何无法在initState使用EasyLoading.show(status: '');

**Comment by huangjianke** [comment]
@CoderTitan  有报错日志么？

example里面是可以在`initState`中使用的 https://github.com/huangjianke/flutter_easyloading/blob/9d9387668b31e3e8ce69f47cc55f6754a26851cb/example/lib/main.dart#L66

**Comment by CoderTitan** [comment]
我之前使用的1.1.4的版本, 是不行的
我现在升级到最新的2.0.0, 就直接报错了, 对flutter版本也有要求嘛?
我的Flutter 1.20.1, Dart 2.9.0
![image](https://user-images.githubusercontent.com/17866726/97123652-c5a61b80-1767-11eb-87a0-ab52b5c44e5d.png)

**Comment by huangjianke** [comment]
@CoderTitan 初始化问题，2.0.0版本请使用以下方式初始化

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: (BuildContext context, Widget child) {
        /// make sure that loading can be displayed in front of all other widgets
        return FlutterEasyLoading(child: child);
      },
    );
  }
}
```
