### ISSUE TITLE
The customer style is invalid!

### ISSUE THREAD

**Issue by leekoo3** [huangjianke/flutter_easyloading#56]
EasyLoading.instance
      ..displayDuration = const Duration(milliseconds: 2000)
      ..indicatorType = EasyLoadingIndicatorType.fadingCircle
      ..loadingStyle = EasyLoadingStyle.dark
      ..indicatorSize = 45.0
      ..radius = 10.0
      ..backgroundColor = Colors.green
      ..indicatorColor = Colors.yellow
      ..textColor = Colors.yellow
      ..maskColor = Colors.blue.withOpacity(0.5);
    EasyLoading.show(status: text);

but the style is not change

**Comment by huangjianke** [comment]
you should set `loadingStyle` to `EasyLoadingStyle.custom`
@leekoo3
