### ISSUE TITLE
初始化 

### ISSUE THREAD

**Issue by 979881765** [huangjianke/flutter_easyloading#57]
builder: ExtendedNavigator.builder(
              router: RouterMap(), guards: [LoginGuard()]),

这种情况下怎样包裹初始化呀？谢谢

**Comment by huangjianke** [comment]
`ExtendedNavigator` 是怎样的结构 @979881765

**Comment by 979881765** [comment]
ExtendNavigator是auto_route库的一个扩展组件

**Comment by 979881765** [comment]
结构如下    lass ExtendedNavigator<T extends RouterBase> extends StatefulWidget {
  static TransitionBuilder builder<T extends RouterBase>({
    GlobalKey<NavigatorState> navigatorKey,
    List<NavigatorObserver> observers = const [],
    RouteFactory onUnknownRoute,
    String initialRoute,
    Object initialRouteArgs,
    @required T router,
    List<RouteGuard> guards = const [],
    String name,
    TransitionBuilder builder,
  }) =>
      (context, nav) {
        var extendedNav = ExtendedNavigator<T>(
          key: GlobalObjectKey(nav.key),
          navigatorKey: navigatorKey,
          observers: observers,
          onUnknownRoute: onUnknownRoute,
          initialRoute: initialRoute,
          initialRouteArgs: initialRouteArgs,
          router: router,
          guards: guards,
          name: name,
        );
        if (builder != null) {
          return builder(context, extendedNav);
        }
        return extendedNav;
      };

**Comment by huangjianke** [comment]
试试这样：

```dart
ExtendedNavigator.builder(
        router: Router(),
        builder: (context, extendedNav) => FlutterEasyLoading(child: extendedNav),
)
```

**Comment by 979881765** [comment]
感谢，这种方式可以解决------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;huangjianke&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月3日(星期二) 下午5:48
收件人:&nbsp;&quot;huangjianke/flutter_easyloading&quot;<flutter_easyloading@noreply.github.com&gt;;
抄送:&nbsp;&quot;丶 bless&quot;<960101847@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [huangjianke/flutter_easyloading] 初始化  (#57)
