### ISSUE TITLE
EasyLoadingContainerState Dismiss 

### ISSUE THREAD

**Issue by Sampan-Lee** [huangjianke/flutter_easyloading#58]
**使用场景**
在dio的请求拦截器中使用EasyLoading.show();   
在dio的返回拦截器中使用EasyLoading.dismiss();
在请求完成后方法外部使用EasyLoading.success();  

**问题复现**

顺序执行  
EasyLoading.show();  
EasyLoading.dismiss();  
EasyLoading.success();  

**问题描述**
EasyLoading.success弹框会马上消失
EasyLoading instance的displayDuration参数不生效
EasyLoading.success的duration参数也不生效

**问题分析**
EasyLoading.dismiss animation参数为true时，
EasyLoadingContainerState.dismiss完成前EasyLoading.success已经执行
调用_reset()方法前，success弹框已经在当前堆栈中  
执行_reset()方法 success弹框迅速消失

**Comment by huangjianke** [comment]
@Sampan-Lee 我尝试复现下

**Comment by Sampan-Lee** [comment]
**临时解决方案**
使用EasyLoading.dismiss(animation:false);代替  
取消动画执行时间以便代码同步执行

**Comment by huangjianke** [comment]
请更新v2.0.1
