### ISSUE TITLE
异步环境中无法被正常调起

### ISSUE THREAD

**Issue by CNMathon** [huangjianke/flutter_easyloading#60]
我似乎遇到了 #50 中同样的问题。

无异步操作则可以正常使用，一旦放置于异步请求后便无法正常调用，且无任何内部报错被抛出。

**Comment by huangjianke** [comment]
@CNMathon 可否提供一个可复现的demo？

**Comment by CNMathon** [comment]
> @CNMathon 可否提供一个可复现的demo？

实在抱歉，已经解决了，是业务逻辑调用错误。但还是感谢作者的及时跟进😀
