### ISSUE TITLE
dismiss异步

### ISSUE THREAD

**Issue by CNAD666** [huangjianke/flutter_easyloading#61]
dismiss这个方法异步操作真的让我很费解，弄成异步的问题，我描述下：
- 某种场景，一个页面提交表单后（提交完后调用dismiss），立马跳转到下个页面，下个页面初始化时需要调用一堆接口，此时开启加载动画，同样是异步操作，此时上个页面异步dismiss此时就会调用，会关闭当前页面的加载动画。

我看了下dismiss里面异步代码，也没啥异步取消操作，就算你搞成异步也没关系，至少要把返回类型搞成Future啊，至少能让我await dismiss结束，而不是让他在某个不确定的时间，跑出来执行不符合预期的效果。

**Comment by huangjianke** [comment]
@CNAD666 确实，我下个版本调整下。谢谢

**Comment by huangjianke** [comment]
@CNAD666 请问下，你目前用的版本是哪个？

**Comment by CNAD666** [comment]
> @CNAD666 请问下，你目前用的版本是哪个？

2.0.1

**Comment by lancelot-song** [comment]
我也遇到了同样的问题，版本 2.1.1

**Comment by huangjianke** [comment]
@lancelot-song 可否提供一个可复现的demo

**Comment by huangjianke** [comment]
> > @CNAD666 请问下，你目前用的版本是哪个？
> 
> 2.0.1

试试 2.1.1 版本
