### ISSUE TITLE
执行了几次dismiss后再执行dissmiss无效了

### ISSUE THREAD

**Issue by cherrybiu** [huangjianke/flutter_easyloading#64]
上传图片时需要显示loading, 使用了`EasyLoading.show(status: '上传头像中…', dismissOnTap: false);`,使用try{}catch(){}来捕捉，最终都会EasyLoadin.dismiss()掉，但是在无网状态下上传了两次消失之后再点击上传，这个loading框就再也不消失了，但是通过输出确认代码是走到了EasyLoading.dismiss()这一行的,想知道是啥原因

**Comment by cherrybiu** [comment]
```
       try {
              EasyLoading.show(status: '上传头像中…', dismissOnTap: false);
              final user = await ...;
              EasyLoading.dismiss();
            } catch (e) {
              print('updateFace $e');
              EasyLoading.dismiss();
              showCustomToast('上传头像失败，请稍后重试');
            }
```

这是相关代码

**Comment by huangjianke** [comment]
@cherrybiu 有断点看下吗？或者帮忙提供一个可复现的demo，我看看

**Comment by huangjianke** [comment]
@cherrybiu 

这个问题的原因是，`show` 还没执行完毕，立马调用了 `dismiss`，先用 `await` 吧，后面我优化下

```dart
    try {
    await  EasyLoading.show(status: '上传头像中…', dismissOnTap: false);
    await  EasyLoading.dismiss();
    } catch (e) {
     await EasyLoading.dismiss();
    }
```

**Comment by cherrybiu** [comment]
确实是这个原因，现在可以了，感恩~

**Comment by huangjianke** [comment]
v2.1.3 已修复这个问题

**Comment by slavap** [comment]
@cherrybiu @huangjianke I'm sorry guys, but could you please use English, not everyone is able to read what you are talking about. Google Translate helps of course, but it is not very polite considering developers from all around the world.

**Comment by huangjianke** [comment]
@slavap got it, thx

**Comment by slavap** [comment]
@huangjianke 
And question: should await is always be used when calling show/dismiss ? Or after your fix it doesn't matter and will work without await? Because in my code I've never used await for show/dismiss, so it worked only because my fetches are slow enough?

**Comment by huangjianke** [comment]
@slavap

Now await is unnecessary but recommended
