### ISSUE TITLE
ios14,打开直接报错了

### ISSUE THREAD

**Issue by x2201783** [huangjianke/flutter_easyloading#67]
flutter:   Overlay
flutter:   file:///Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-2.2.0/lib/src/widgets/loading.dart:62:14                 
定位到   child: Overlay(。这行出错了。

我的环境是14.1，我之前用13的系统是好的
  void main() {

  runApp(

  FlutterEasyLoading(

    child: MaterialApp(

        home: AppRoot(),

    ),
  ));
       //configLoading();
}
class AppRoot extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

**Comment by huangjianke** [comment]
@x2201783 最新版的初始化方式有变化

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: EasyLoading.init(),
    );
  }
}
```
