### ISSUE TITLE
请问有没有弹出loading框的时候，让下面的ui都无法操作啊

### ISSUE THREAD

**Issue by xinlee333** [huangjianke/flutter_easyloading#69]
比如我点了登录按钮，弹出loading转圈，那我希望在服务器返回消息前不能再次点击loading按钮，同时也不能点击其他的ui，这个功能现在有吗？谢谢。

**Comment by huangjianke** [comment]
@xinlee333 set userInteractions to false

**Comment by Willdas** [comment]
我是在初始化时这么设置的，发现还是可以使用物理键返回按钮，返回，并且样式居然还显示着。

**Comment by Willdas** [comment]
@kokohuang
