### ISSUE TITLE
如果在刚进入一个页面的时候就显示easyloading.show，我该在哪里调用呢

### ISSUE THREAD

**Issue by NSChris** [huangjianke/flutter_easyloading#7]
比如我刚进入一个页面
在他的initState我在后台取数据，这时候需要一个loading显示，然后取完数据loading消失
<img width="487" alt="image" src="https://user-images.githubusercontent.com/4965700/76492271-c0ab8a80-646a-11ea-9145-d28967a7b668.png">
像我上面这样调用的话会报出找不到buildContext的错误
<img width="356" alt="image" src="https://user-images.githubusercontent.com/4965700/76492347-f18bbf80-646a-11ea-9e3d-c93e3b79c921.png">
那我要怎么调用它呢，谢谢

**Comment by huangjianke** [comment]
@NSChris 
可以提供一个可复现的demo么
另外，Flutter版本是什么

**Comment by NSChris** [comment]
@huangjianke 
版本的话
Flutter 1.12.13+hotfix.8 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

demo新建一个如下的Home.dart文件
import 'package:flutter/material.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';

class HomePage extends StatefulWidget {
  HomePage({Key key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  void initState() {
    super.initState();
    setDS();
  }

  void setDS() {
    // EasyLoading.show(status:"请稍等...");
    //获取数据
  }

  @override
  Widget build(BuildContext context) {
    return FlutterEasyLoading(
        child: Container(
      child: Text("data"),
    ));
  }
}

**Comment by huangjianke** [comment]
> @huangjianke
> 版本的话
> Flutter 1.12.13+hotfix.8 • channel stable •
> https://github.com/flutter/flutter.git
> Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
> Engine • revision e1e6ced81d
> Tools • Dart 2.7.0
> 
> demo新建一个如下的Home.dart文件
> import 'package:flutter/material.dart';
> import 'package:flutter_easyloading/flutter_easyloading.dart';
> 
> class HomePage extends StatefulWidget {
> HomePage({Key key}) : super(key: key);
> 
> @override
> _HomePageState createState() => _HomePageState();
> }
> 
> class _HomePageState extends State {
> @override
> void initState() {
> super.initState();
> setDS();
> }
> 
> void setDS() {
> // EasyLoading.show(status:"请稍等...");
> //获取数据
> }
> 
> @override
> Widget build(BuildContext context) {
> return FlutterEasyLoading(
> child: Container(
> child: Text("data"),
> ));
> }
> }

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return FlutterEasyLoading(
      child: MaterialApp(
        title: 'Flutter EasyLoading',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage(title: 'Flutter EasyLoading'),
      ),
    );
  }
}
```

确认下这里是否有用 `FlutterEasyLoading`组件作为根组件？

**Comment by NSChris** [comment]
@huangjianke 
在main.dart里面是加入了的
我在Container里面加入的按钮onTap事件里调用show是没有问题的
<img width="366" alt="image" src="https://user-images.githubusercontent.com/4965700/76494605-31a17100-6470-11ea-8695-c8a6ff7b89d7.png">

**Comment by NSChris** [comment]
我觉得是因为initState()的生命周期是在BuildContext之前的
我在那里面调用是找不到context的

**Comment by huangjianke** [comment]
> 我觉得是因为initState()的生命周期是在BuildContext之前的
> 我在那里面调用是找不到context的

好的，我调试下

**Comment by huangjianke** [comment]
@NSChris 

我在dev分支调整了下，你那边本地可以修改一下试试，我这边再测试下，后面没什么问题会尽快发布新版。

感谢反馈

**Comment by NSChris** [comment]
@huangjianke 
改了已经可以了，然后现在我又发现一个问题就是在页面有bottomNavigationBar和floatingActionButton的框架下，loading的mask不能把下面的tabs和悬浮按钮遮挡住，这个是我没用对吗
<img width="366" alt="image" src="https://user-images.githubusercontent.com/4965700/76500755-14729f80-647c-11ea-8012-13baa09b8dd8.png">

**Comment by huangjianke** [comment]
> @huangjianke
> 改了已经可以了，然后现在我又发现一个问题就是在页面有bottomNavigationBar和floatingActionButton的框架下，loading的mask不能把下面的tabs和悬浮按钮遮挡住，这个是我没用对吗
> <img alt="image" width="366" src="https://user-images.githubusercontent.com/4965700/76500755-14729f80-647c-11ea-8012-13baa09b8dd8.png">

![image](https://user-images.githubusercontent.com/8692455/76502859-c52e6e00-647f-11ea-9b34-4b3a77c5da92.png)
我这边测试是正常的，确认下`FlutterEasyLoading`是不是App的根组件？

**Comment by NSChris** [comment]
@huangjianke 
啊.. 确实 刚才测试那个initState的时候把FlutterEasyLoading放到了home下面
是没问题的，谢谢

**Comment by huangjianke** [comment]
> @huangjianke
> 啊.. 确实 刚才测试那个initState的时候把FlutterEasyLoading放到了home下面
> 是没问题的，谢谢

好的。

**Comment by huangjianke** [comment]
@NSChris 发布了新版，在 `initState ` 中可以这样使用

  ```dart
  WidgetsBinding.instance.addPostFrameCallback((_) {
    EasyLoading.showSuccess('Great Success!');
  });
  ```

**Comment by NSChris** [comment]
好的 我晚上试试 谢谢提醒

**Comment by NSChris** [comment]
@huangjianke 好的 我晚上试试 谢谢提醒

**Comment by NSChris** [comment]
@huangjianke 换上了是可以用，但是感觉没有之前用着方便，暂时这样用吧

**Comment by huangjianke** [comment]
> @huangjianke 换上了是可以用，但是感觉没有之前用着方便，暂时这样用吧

因为在 `initState` 中使用相对来说比较特殊，上一个版本尝试着在内部使用 `WidgetsBinding.instance.addPostFrameCallback` 来解决这个问题，后来发现会引起其他的一些bug，我后面会继续跟进这个问题。

**Comment by NSChris** [comment]
好的 先这样用着
