### ISSUE TITLE
Failed assertion: line 552 pos 15: 'textDirection != null': is not true.

### ISSUE THREAD

**Issue by Rahuldavaskar** [huangjianke/flutter_easyloading#71]
Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Overlay(state: OverlayState#d3586(entries: [EasyLoadingOverlayEntry#02a68(opaque: false; maintainState: false), EasyLoadingOverlayEntry#e98a8(opaque: false; maintainState: false)])):
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 552 pos 15: 'textDirection != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Overlay file:///C:/Users/Rahul%20Davaskar/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-2.2.0/lib/src/widgets/loading.dart:62:14
When the exception was thrown, this was the stack: 
#2      new _RenderTheatre (package:flutter/src/widgets/overlay.dart:552:15)
#3      _Theatre.createRenderObject (package:flutter/src/widgets/overlay.dart:509:12)
#4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5491:28)
#5      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:11)
...     Normal element mounting (59 frames)
...

**Comment by huangjianke** [comment]
```dart

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter EasyLoading',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter EasyLoading'),
      builder: EasyLoading.init(),
    );
  }
}

```

@Rahuldavaskar you should init in your root app

**Comment by Rahuldavaskar** [comment]
thank you @huangjianke
