### ISSUE TITLE
'_overlay != null' error

### ISSUE THREAD

**Issue by genius1212** [huangjianke/flutter_easyloading#8]
use  EasyLoading.show(status: "loading..."); Error!

error stack:
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 132 pos 12: '_overlay != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:132:12)
#3      EasyLoading._remove (package:flutter_easyloading/src/easy_loading.dart:353:34)
#4      EasyLoading._show (package:flutter_easyloading/src/easy_loading.dart:323:5)
#5      EasyLoading.show (package:flutter_easyloading/src/easy_loading.dart:165:20)
#6      OrderAction.getOrderDetail (package:novo/action/order_action.dart:156:17)
#7      _OrderDetailState.initState (package:novo/page/order/order_detail.dart:66:19)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#10     Element.inflat<…>

this place:
void _remove() {
    _getInstance().overlayEntry?.remove();
    _getInstance()._overlayEntry = null;
    _getInstance()._key = null;
    _getInstance()._progress = null;
    _getInstance()._progressKey = null;
  }

**Comment by huangjianke** [comment]
@genius1212 
Hi! show me your code and please run `flutter doctor` then put info here
thanks.

**Comment by genius1212** [comment]
![1584409983501](https://user-images.githubusercontent.com/59531737/76814195-18fcd680-6835-11ea-93a3-313ee3d33fd8.jpg)
![1584410204175](https://user-images.githubusercontent.com/59531737/76814381-97f20f00-6835-11ea-958b-be7eeb93d783.jpg)
this is my code, thank you!

**Comment by genius1212** [comment]
i modified here，
..userInteractions = false;

**Comment by huangjianke** [comment]
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    /// child should be [MaterialApp] or [CupertinoApp].
    /// make sure that loading can be displayed in front of all other widgets
    return FlutterEasyLoading(
      child: MaterialApp(
        title: 'Flutter EasyLoading',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage(title: 'Flutter EasyLoading'),
      ),
    );
  }
}
```

Do you have use  `FlutterEasyLoading` wrap your `MaterialApp`?

**Comment by genius1212** [comment]
> ```dart
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     /// child should be [MaterialApp] or [CupertinoApp].
>     /// make sure that loading can be displayed in front of all other widgets
>     return FlutterEasyLoading(
>       child: MaterialApp(
>         title: 'Flutter EasyLoading',
>         theme: ThemeData(
>           primarySwatch: Colors.blue,
>         ),
>         home: MyHomePage(title: 'Flutter EasyLoading'),
>       ),
>     );
>   }
> }
> ```
> 
> Do you have use `FlutterEasyLoading` wrap your `MaterialApp`?

no use

**Comment by huangjianke** [comment]
> > ```dart
> > class MyApp extends StatelessWidget {
> >   @override
> >   Widget build(BuildContext context) {
> >     /// child should be [MaterialApp] or [CupertinoApp].
> >     /// make sure that loading can be displayed in front of all other widgets
> >     return FlutterEasyLoading(
> >       child: MaterialApp(
> >         title: 'Flutter EasyLoading',
> >         theme: ThemeData(
> >           primarySwatch: Colors.blue,
> >         ),
> >         home: MyHomePage(title: 'Flutter EasyLoading'),
> >       ),
> >     );
> >   }
> > }
> > ```
> > 
> > 
> > Do you have use `FlutterEasyLoading` wrap your `MaterialApp`?
> 
> no use

try it

**Comment by genius1212** [comment]
It works, thank you!

**Comment by genius1212** [comment]
the problem still exists, 
//
_timer = Timer.periodic(Duration(seconds: 1), (Timer timer){
     EasyLoading.showToast('Toast');
     _timer?.cancel();
});

**Comment by genius1212** [comment]
When the toast is in the Timer, it makes an error

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 132 pos 12: '_overlay != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:132:12)
#3      EasyLoading._remove (package:flutter_easyloading/src/easy_loading.dart:353:34)
#4      EasyLoading.dismiss (package:flutter_easyloading/src/easy_loading.dart:284:20)
#5      EasyLoading._show.<anonymous closure> (package:flutter_easyloading/src/easy_loading.dart:342:9)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#9      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:970:26)
#10     _rootRunUnary (dart:async/zone.dart:1138:13)
#11     _Cust<…>

**Comment by huangjianke** [comment]
> The problem still exists,
> It will appear in the timer
> //
> _timer = Timer.periodic(Duration(seconds: 1), (Timer timer){
> EasyLoading.showToast('Toast');
> _timer?.cancel();
> });

i will check it soon

**Comment by huangjianke** [comment]
@genius1212 hi, the bug is fixed, thanks for your feedback

```yaml
dependencies:
  flutter_easyloading: ^1.1.3
```

**Comment by genius1212** [comment]
> @genius1212 hi, the bug is fixed, thanks for your feedback
> 
> ```yaml
> dependencies:
>   flutter_easyloading: ^1.1.3
> ```

That’s great!

**Comment by robertcsouza** [comment]
you need put  in main builder: EasyLoading.init();

`MaterialApp(
      title: 'Flutter Demo',
      initialRoute: '/',
      routes: routes(),
      builder: EasyLoading.init(),
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
`
