### ISSUE TITLE
Need option to set line width

### ISSUE THREAD

**Issue by karthikAdaptavant** [huangjianke/flutter_easyloading#9]
Can you pls open an option to set ring line width. the default is too thick. 
![Screen Shot 2020-03-21 at 9 00 08 PM](https://user-images.githubusercontent.com/11072850/77229975-f8c37380-6bb6-11ea-9804-31b3f0ef2e4f.png)

**Comment by karthikAdaptavant** [comment]
Help much appriciated, Thanks in advance

**Comment by huangjianke** [comment]
@karthikAdaptavant ok

**Comment by huangjianke** [comment]
@karthikAdaptavant 

the latest version has added lineWidth option

```dart
/// width of indicator, default 4.0, only used for [EasyLoadingIndicatorType.ring, EasyLoadingIndicatorType.dualRing].
double lineWidth;
```
